# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='customer.proto',
  package='customer',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x63ustomer.proto\x12\x08\x63ustomer\"\xdf\x01\n\x0f\x43ustomerRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\x34\n\taddresses\x18\x05 \x03(\x0b\x32!.customer.CustomerRequest.Address\x1a^\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x19\n\x11isShippingAddress\x18\x05 \x01(\x08\"/\n\x10\x43ustomerResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"!\n\x0e\x43ustomerFilter\x12\x0f\n\x07keyword\x18\x01 \x01(\t2\x9e\x01\n\x08\x43ustomer\x12G\n\x0cGetCustomers\x12\x18.customer.CustomerFilter\x1a\x19.customer.CustomerRequest\"\x00\x30\x01\x12I\n\x0e\x43reateCustomer\x12\x19.customer.CustomerRequest\x1a\x1a.customer.CustomerResponse\"\x00\x62\x06proto3')
)




_CUSTOMERREQUEST_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='customer.CustomerRequest.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='street', full_name='customer.CustomerRequest.Address.street', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='customer.CustomerRequest.Address.city', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='customer.CustomerRequest.Address.state', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zip', full_name='customer.CustomerRequest.Address.zip', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isShippingAddress', full_name='customer.CustomerRequest.Address.isShippingAddress', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=252,
)

_CUSTOMERREQUEST = _descriptor.Descriptor(
  name='CustomerRequest',
  full_name='customer.CustomerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='customer.CustomerRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='customer.CustomerRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='customer.CustomerRequest.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone', full_name='customer.CustomerRequest.phone', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addresses', full_name='customer.CustomerRequest.addresses', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CUSTOMERREQUEST_ADDRESS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=252,
)


_CUSTOMERRESPONSE = _descriptor.Descriptor(
  name='CustomerResponse',
  full_name='customer.CustomerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='customer.CustomerResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='customer.CustomerResponse.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=301,
)


_CUSTOMERFILTER = _descriptor.Descriptor(
  name='CustomerFilter',
  full_name='customer.CustomerFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyword', full_name='customer.CustomerFilter.keyword', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=336,
)

_CUSTOMERREQUEST_ADDRESS.containing_type = _CUSTOMERREQUEST
_CUSTOMERREQUEST.fields_by_name['addresses'].message_type = _CUSTOMERREQUEST_ADDRESS
DESCRIPTOR.message_types_by_name['CustomerRequest'] = _CUSTOMERREQUEST
DESCRIPTOR.message_types_by_name['CustomerResponse'] = _CUSTOMERRESPONSE
DESCRIPTOR.message_types_by_name['CustomerFilter'] = _CUSTOMERFILTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomerRequest = _reflection.GeneratedProtocolMessageType('CustomerRequest', (_message.Message,), dict(

  Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), dict(
    DESCRIPTOR = _CUSTOMERREQUEST_ADDRESS,
    __module__ = 'customer_pb2'
    # @@protoc_insertion_point(class_scope:customer.CustomerRequest.Address)
    ))
  ,
  DESCRIPTOR = _CUSTOMERREQUEST,
  __module__ = 'customer_pb2'
  # @@protoc_insertion_point(class_scope:customer.CustomerRequest)
  ))
_sym_db.RegisterMessage(CustomerRequest)
_sym_db.RegisterMessage(CustomerRequest.Address)

CustomerResponse = _reflection.GeneratedProtocolMessageType('CustomerResponse', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMERRESPONSE,
  __module__ = 'customer_pb2'
  # @@protoc_insertion_point(class_scope:customer.CustomerResponse)
  ))
_sym_db.RegisterMessage(CustomerResponse)

CustomerFilter = _reflection.GeneratedProtocolMessageType('CustomerFilter', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMERFILTER,
  __module__ = 'customer_pb2'
  # @@protoc_insertion_point(class_scope:customer.CustomerFilter)
  ))
_sym_db.RegisterMessage(CustomerFilter)



_CUSTOMER = _descriptor.ServiceDescriptor(
  name='Customer',
  full_name='customer.Customer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=339,
  serialized_end=497,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCustomers',
    full_name='customer.Customer.GetCustomers',
    index=0,
    containing_service=None,
    input_type=_CUSTOMERFILTER,
    output_type=_CUSTOMERREQUEST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateCustomer',
    full_name='customer.Customer.CreateCustomer',
    index=1,
    containing_service=None,
    input_type=_CUSTOMERREQUEST,
    output_type=_CUSTOMERRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUSTOMER)

DESCRIPTOR.services_by_name['Customer'] = _CUSTOMER

# @@protoc_insertion_point(module_scope)
