# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "customer.CustomerRequest" do
    optional :id, :int32, 1
    optional :name, :string, 2
    optional :email, :string, 3
    optional :phone, :string, 4
    repeated :addresses, :message, 5, "customer.CustomerRequest.Address"
  end
  add_message "customer.CustomerRequest.Address" do
    optional :street, :string, 1
    optional :city, :string, 2
    optional :state, :string, 3
    optional :zip, :string, 4
    optional :isShippingAddress, :bool, 5
  end
  add_message "customer.CustomerResponse" do
    optional :id, :int32, 1
    optional :success, :bool, 2
  end
  add_message "customer.CustomerFilter" do
    optional :keyword, :string, 1
  end
end

module Customer
  CustomerRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("customer.CustomerRequest").msgclass
  CustomerRequest::Address = Google::Protobuf::DescriptorPool.generated_pool.lookup("customer.CustomerRequest.Address").msgclass
  CustomerResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("customer.CustomerResponse").msgclass
  CustomerFilter = Google::Protobuf::DescriptorPool.generated_pool.lookup("customer.CustomerFilter").msgclass
end
