# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: customer.proto for package 'customer'

require 'grpc'
require 'customer_pb'

module Customer
  module Customer
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'customer.Customer'

      rpc :GetCustomers, CustomerFilter, stream(CustomerRequest)
      rpc :CreateCustomer, CustomerRequest, CustomerResponse
    end

    Stub = Service.rpc_stub_class
  end
end
